### ISSUE TITLE
Release webpack compiler as npm package?

### ISSUE THREAD

**Issue by karlhorky** [alexfedoseev/test-webpack-specific-builds-with-mocha#1]
Would you consider releasing [the webpack compiler](https://github.com/alexfedoseev/test-webpack-specific-builds-with-mocha/blob/master/app/utils/tests/compiler.js) as a standalone npm package for easier use? Kind of like the [`babel-register`](https://babeljs.io/docs/usage/require/) package for babel?

Thanks for the nice project!

**Comment by alexfedoseev** [comment]
@karlhorky It's a good idea. Currently we're about to implement it on product project, after we'll finish implementation — I'll release it as a stand-alone npm package. I'll keep this issue open for now, thanks! :+1:

**Comment by karlhorky** [comment]
Cool, nice to hear. Looking forward to it!

**Comment by djschilling** [comment]
Is there any progress on this?

**Comment by alexfedoseev** [comment]
@djschilling Sorry, nope, I switched to [Jest](https://facebook.github.io/jest/docs/webpack.html#configuring-jest-to-find-our-files).
